manifest:

  projects:
    - name: zephyr
      revision: v3.7.1
      path: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr.git
      import:
        name-allowlist:
          - cmsis
          - hal_xtensa
          - lvgl
          - mbedtls
          - mcuboot
          - trusted-firmware-m

    - name: wasm-micro-runtime
      revision: main
      path: wasm-zephyr-ota/libs/wasm-micro-runtime
      url: https://github.com/bytecodealliance/wasm-micro-runtime.git

  self:
    path: wasm-zephyr-ota
